# Generated by Django 3.0.6 on 2020-05-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200515_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transection_id',
            new_name='transaction_id',
        ),
    ]
